# Generated by Django 6.0.5 on 2026-05-20 08:30

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar[list[tuple[str, str]]] = [
    ("scanner", "0001_initial"),
    ]

    operations: ClassVar[list] = [
        migrations.AlterField(
            model_name="targetsearch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
